Updated documentation for Windows setup
bmw-software-engineering/trlc pull request #105
Opened 2024-09-16 12:33 UTC by SurajBDeore

Platform-Specific Setup Instructions
 
This update adds separate setup instructions for both Linux and Windows environments:
 
-  Windows: Added steps for installing required tools using the Scoop package manager, including `findutils` and `make`.

-  Linux: Clarified package installation for `build-essential` and `graphviz` using native package managers.
 
These changes simplify the setup process and ensure compatibility across platforms for contributors.

2024-10-04 12:46 UTC, christophkloeffel requested changes

2024-10-04 12:46 UTC, christophkloeffel commented on documentation/dev_setup.md
> +      scoop install Graphviz
please fix indentation

2024-10-04 12:46 UTC, christophkloeffel commented on documentation/dev_setup.md
>      ```bash
please also fix indentation

2024-10-04 12:46 UTC, christophkloeffel commented on documentation/dev_setup.md
> +
please avoid cluttering the version control by adding spaces in blank lines

2024-10-04 12:46 UTC, christophkloeffel commented on documentation/dev_setup.md
> +
```suggestion
To contribute to TRLC, you will need to be able to run the
testsuite. Therefore you need GNU make and GNU findutils.
We do provide setup steps for Windows and Linux. If you run into any problems on macOS, make sure you install the latest GNU make version.
```

2024-10-04 12:46 UTC, christophkloeffel commented on documentation/dev_setup.md
> +
It is possible on macOS for sure. I think the only hindrance could be an outdated make version

2024-10-31 08:09 UTC, phiwuu requested changes

2024-10-31 08:09 UTC, phiwuu commented on documentation/dev_setup.md
> +  * Check out https://scoop.sh/
please remove the extra bullet point:
```
* You need to Install Scoop.
  Check out https://scoop.sh/
```

2024-11-04 09:43 UTC, christophkloeffel approved these changes

2024-11-07 17:11 UTC, phiwuu approved these changes

2024-11-07 17:24 UTC, merged