adds tracing for checks
bmw-software-engineering/trlc pull request #34
Opened 2023-10-09 06:33 UTC by christophkloeffel

adds tracing for chapter 10

2023-10-09 10:33 UTC, florianschanda requested changes
### LRM.Check_Block

Needs link to:
* `ast.Check_Block`
* `ast.Check`

### LRM.Check_Evaluation_Order

Needs link to:
* `ast.Record_Object.perform_checks`
* `ast.Composite_Type.add_check`
* `ast.Composite_Type.iter_checks`
* `ast.Record_Type.iter_checks`
* `ast.Tuple_Type.perform_type_checks`

### LRM.Check_Evaluation_Order_For_Extensions

I do not think the link to `parser.Parser.parse_check_block` makes a
lot of sense.

Needs link to:
* `ast.Record_Type.iter_checks`

2023-10-09 10:33 UTC, florianschanda commented on language-reference-manual/lrm.trlc
> +      untraced_reason = "Example code"
Illegal - CI should have complained about this:
```
untraced_reason = "Example code"
^^^^^^^^^^^^^^^ language-reference-manual/lrm.trlc:1004: error: cannot overwrite frozen component untraced_reason
```

I have created https://github.com/bmw-software-engineering/trlc/issues/37 to fix that.

2023-10-09 10:33 UTC, florianschanda commented on language-reference-manual/lrm.trlc
> +  Note Check_Evaluation_Order_Across_Blocks {
Good point. This is actually also a bug in the linter, and I have created https://github.com/bmw-software-engineering/trlc/issues/36 to fix it.

2023-10-09 10:33 UTC, florianschanda commented on tests-system/checks-10/tracing
> +LRM.Applicable_Components
Like with PR #35 please use the `rbt-` naming scheme for new tests that test specific requirements.

2023-10-15 18:53 UTC, christophkloeffel commented
> ### LRM.Check_Block
> Needs link to:
> 
> * `ast.Check_Block`
> * `ast.Check`
> 
After tracing a class it is not possible to trace the methods within anymore. They get ignored in the tracing report. Is this intended? 

as of now `LRM.Check_Messages` and `LRM.Check_Severity` are not traced to `ast.Check.perform`

2023-10-20 09:37 UTC, merged