removes the builtin function syntax
bmw-software-engineering/trlc pull request #52
Opened 2023-10-30 15:16 UTC by christophkloeffel

2023-10-31 07:54 UTC, florianschanda requested changes
Nice work :)

Removing this means we need to change the major version. It also means we should kill check files at that point and possible make `-I .` the default as well. To be discussed...

Some comments:

lexer.py:

* You need to also remove the `:` option for the identifier loop
  in the lexer, as `:` can no longer be part of a valid name

CHANGELOG.md:

* You need an entry here as well

2023-10-31 07:54 UTC, florianschanda commented on tests-system/builtin-2/legacy.rsl
We should not delete tests, just update the name and/or output.

2024-01-30 11:24 UTC, phiwuu commented
This PR is open for a while now. For me it is okay to step to the next major version now. Shall we merge this PR?

2024-02-02 21:31 UTC, florianschanda commented
We can, but it'd be good to bundle it with some other incompatible changes. Do you have a wishlist?

2024-02-20 11:59 UTC, merged