adds tracing for record object declarations
bmw-software-engineering/trlc pull request #64
Opened 2024-01-16 11:55 UTC by christophkloeffel

adds tracing for chapter 18

2024-01-30 15:19 UTC, phiwuu requested changes

2024-01-30 15:19 UTC, phiwuu commented on language-reference-manual/lrm.trlc
> +  /*Name_Resolution Sufficiently_Distinct {
I recommend to delete this section completely.
The implementation of https://github.com/bmw-software-engineering/trlc/issues/62 will have to add it back.

2024-01-30 15:19 UTC, phiwuu commented on tests-system/lint-ug-examples/output
> -    |     y = 37
I have discussed the issue with @christophkloeffel. It seems the solver finds different solutions on different computers. @florianschanda do you know how to make the solver output deterministic independent of the platform?

2024-01-30 15:19 UTC, phiwuu commented on tests-system/rbt-evaluation-of-checks/foo.rsl
> +}
Either remove the `Tuple` completely, or additionally add a check for `Tuple`, too.
I prefer the short solution: keep the test short and simple and remove `Tuple`.

2024-01-30 15:19 UTC, phiwuu commented on tests-system/rbt-tuple-generic-form/foo.rsl
> +package Foo
`Tuple_Generic_Form` says that values must be provided and parsed in order.
Please consider to test the order like this:
RSL file:
```
package Foo

tuple Tuple {
    a Integer
    b String
}

type T {
    tu Tuple
}
```
TRLC file:
```
T Bar { tu = (1.0, 2.0) }
```
Expectation: `1.0` is a decimal, but Integer expected, `2.0` is a decimal, but String expected.

2024-01-30 15:19 UTC, phiwuu commented on tests-system/rbt-tuple-separator-form/foo.trlc
> +    tu = 1:2@3;4
Please also add a good case

2024-09-02 11:30 UTC, christophkloeffel commented on language-reference-manual/lrm.trlc
> +  /*Name_Resolution Sufficiently_Distinct {
implemented by https://github.com/bmw-software-engineering/trlc/commit/1a34b700c7974976239033317774b7e6eeb2bf65

2024-09-02 11:31 UTC, christophkloeffel commented on tests-system/lint-ug-examples/output
> -    |     y = 37
solved with information from #78

2024-09-02 12:35 UTC, phiwuu approved these changes

2024-09-02 12:47 UTC, merged