adds tracing for markup strings
bmw-software-engineering/trlc pull request #67
Opened 2024-01-16 11:56 UTC by christophkloeffel

adds tracing for chapter 19

2024-02-06 11:54 UTC, phiwuu requested changes

2024-02-06 11:54 UTC, phiwuu commented on tests-system/lint-ug-examples/output
> -    |     x = 3
Please revert

2024-02-06 11:54 UTC, phiwuu commented on trlc/ast.py
> +        # lobster-trace: LRM.Markup_String_Late_Reference_Resolution
move to https://github.com/bmw-software-engineering/trlc/blob/92947777b0d034c37b2db1fb82502c420ca50326/trlc/trlc.py#L507 instead (function `resolve_record_references` in `trlc.py`)

2024-02-06 11:54 UTC, phiwuu commented on trlc/parser.py
> +
remove empty line

2024-02-06 11:54 UTC, phiwuu commented on trlc/trlc.py
> +        # lobster-trace: LRM.Markup_String_Late_Reference_Resolution
move into function `resolve_record_references`, see comment above

2024-02-06 11:54 UTC, phiwuu commented on trlc/parser.py
> +        # lobster-trace: LRM.Markup_String_Late_Reference_Resolution
delete here, see other comments

2024-09-02 10:04 UTC, christophkloeffel commented on tests-system/lint-ug-examples/output
> -    |     x = 3
fixed with options file like florian mentioned #78

2024-09-02 12:42 UTC, phiwuu submitted a review, later dismissed

2024-10-15 12:02 UTC, phiwuu approved these changes

2024-10-24 12:54 UTC, merged