remove deprecated feature: check files
bmw-software-engineering/trlc pull request #74
Opened 2024-03-20 09:48 UTC by ankushsonare1

2024-03-26 09:04 UTC, christophkloeffel requested changes
Please also create a new entry in https://github.com/bmw-software-engineering/trlc/blob/main/CHANGELOG.md

2024-03-26 09:04 UTC, christophkloeffel commented on trlc/trlc.py
>              summary += ","
also not needed anymore, because it would produce something like this:
"Processed 1 model, and 1 requirement file and found 3 errors"
But we want
"Processed 1 model and 1 requirement file and found 3 errors"

"," was only needed when number of filetypes > 2. We removed .check files. So we only have two left (.rsl and .trlc). Therefore we don't need "," anymore

2024-03-26 09:04 UTC, christophkloeffel commented on trlc/trlc.py
> -        ok &= self.parse_check_files()
please remove the dead code

2024-03-26 09:23 UTC, christophkloeffel commented on trlc/parser.py
> -        # lobster-trace: LRM.Check_File
If you remove traces to the LRM
Always check if the corresponding content needs to be removed too

2024-03-26 09:28 UTC, christophkloeffel commented
Regarding the LRM: Since we completely remove the support of check files. Please also have a look at the tracing report of LOBSTER
Make sure that the new code matches the LRM

2024-03-28 12:59 UTC, christophkloeffel commented
> Please also create a new entry in https://github.com/bmw-software-engineering/trlc/blob/main/CHANGELOG.md

This is still pending

2024-03-28 13:11 UTC, christophkloeffel requested changes

2024-03-28 13:11 UTC, christophkloeffel commented on language-reference-manual/lrm.trlc
Please also have a look at section 3 and adapt it accordingly

2024-04-22 14:34 UTC, akashsurwase1 submitted a review, later dismissed
ok to merge

2024-05-10 08:50 UTC, akashsurwase1 commented
ok to merge

2024-06-09 08:10 UTC, florianschanda commented
Obsoleted by https://github.com/bmw-software-engineering/trlc/pull/87

2024-06-10 13:16 UTC, closed without merging