Remove warnings regarding duplicate late declaration of packages (#72)
bmw-software-engineering/trlc pull request #75
Opened 2024-03-21 11:33 UTC by mugdhadhole1

ISSUE: #72

2024-03-26 09:19 UTC, christophkloeffel requested changes
Please also create an entry in https://github.com/bmw-software-engineering/trlc/blob/main/CHANGELOG.md

2024-03-26 09:19 UTC, christophkloeffel commented on trlc/parser.py
> -                # lobster-trace: LRM.Duplicate_Late_Packages
this is a trace to the LRM
please have a look at the LRM and also remove the linked content in the LRM

2024-04-16 12:07 UTC, christophkloeffel requested changes
there is a tracing file in "rbt-late-package-declarations" test folder. make sure to delete this, because you deleted the corresponding entry in the LRM

2024-04-22 14:36 UTC, akashsurwase1 approved these changes
ok to merge

2024-04-24 08:28 UTC, christophkloeffel approved these changes

2024-04-24 08:39 UTC, merged