Iteration api by section
bmw-software-engineering/trlc pull request #90
Opened 2024-06-12 14:19 UTC by mugdhadhole1

#12

2024-06-12 19:11 UTC, christophkloeffel requested changes

2024-06-12 19:11 UTC, christophkloeffel commented on trlc/ast.py
>      def dump(self, indent=0):  # pragma: no cover
If the parent attribute changes to a list then have a look at that dump method. you can't call `self.parent.name` on a list. you have to change this
but I would prefer to revert back to a Section, see other comments

2024-06-12 19:11 UTC, christophkloeffel commented on trlc/parser.py
> +        self.match_kw("section")
why do you expect another section keyword here? this leads to the error in the CI
also please always run `make test-all` and `make lint` once locally before you create a PR

2024-06-12 19:11 UTC, christophkloeffel commented on trlc/parser.py
> +                            parent   = self.section.copy())
why do you change the value of parent when you are not using this at all?
you do only use Record_Object.section currently
```suggestion
                            parent   = self.section[-1] if self.section else None
```

2024-06-12 19:11 UTC, christophkloeffel commented on trlc/ast.py
> +                yield record_object.name
a proposal for refactoring the code:
get rid of self.section_dictionary then. not necessary
```suggestion
        object_level = len(record_object.section)-1 if record_object.section else 0
        if record_object.section:
            for level, section in enumerate(record_object.section):
                if section.name not in section_names:
                    section_names.append(section.name)
                    yield section.name, level
            yield record_object, object_level
        else:
            yield record_object, object_level
```

2024-06-12 19:11 UTC, christophkloeffel commented on trlc/ast.py
> +    def iter_record_objects_by_section(self):
add at least some kind of docstring which explains what this method is yielding

2024-06-12 19:17 UTC, christophkloeffel commented on trlc/parser.py
> +            section   = self.section if self.section else None,
is this even working without `self.section.copy()`?

2024-06-13 08:13 UTC, florianschanda commented on trlc/parser.py
> +        self.match_kw("section")
Yeah I am pretty sure this is wrong :) Copy-pasta error?

2024-06-13 08:17 UTC, florianschanda commented
I think instead of just coding something it would be good to first define on #12 what this actually means. I can think of several interfaces:

* a section iterator, which can then be iterated over again to get items
* a modification of the normal iterator that yield sections along normal items; and you then have to recurse
* a iteration via callback similar to http://www.saxproject.org/
* ... something else?

2024-10-14 16:47 UTC, christophkloeffel approved these changes

2024-10-14 16:59 UTC, merged